# Generated by Django 3.2.3 on 2021-05-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='clicks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
