# Generated by Django 3.2.3 on 2021-06-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='boby',
            new_name='body',
        ),
    ]
