# Generated by Django 3.2.3 on 2021-06-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_blogpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_edited',
            field=models.DateTimeField(null=True),
        ),
    ]
