# Generated by Django 3.2.3 on 2021-07-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_delete_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='rant',
        ),
    ]
