# Generated by Django 3.2.3 on 2021-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('wears_glasses', models.BooleanField()),
                ('favorite_int', models.IntegerField()),
                ('favorite_float', models.FloatField()),
                ('birthday', models.DateField()),
            ],
        ),
    ]
