# Generated by Django 3.2.3 on 2021-05-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
