# Generated by Django 3.2.3 on 2021-05-25 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0002_auto_20210525_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contactsapp.city'),
            preserve_default=False,
        ),
    ]
