# Generated by Django 3.2.3 on 2021-06-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='type',
            new_name='types',
        ),
    ]
