# Generated by Django 3.2.3 on 2021-07-30 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_converter_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversion',
        ),
    ]
