# Generated by Django 3.2.3 on 2021-06-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0002_inventoryitem_monsterinventoryitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItem',
            new_name='InventoryItemType',
        ),
    ]
