# Generated by Django 3.2.3 on 2021-07-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0005_monster_monsterinventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='inventory',
            field=models.ManyToManyField(to='dndapp.InventoryItemType'),
        ),
    ]
