# Generated by Django 3.2.3 on 2021-07-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
