# Generated by Django 3.2.3 on 2021-05-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20210526_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
