# Generated by Django 3.2.3 on 2021-05-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
