# Generated by Django 3.2.3 on 2021-06-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeappi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='img_back',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='img_front',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
