# Generated by Django 3.2.3 on 2021-06-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeappi', '0002_auto_20210623_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='img_back',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='img_front',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image_back',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image_front',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
