# Generated by Django 3.2.3 on 2021-07-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeappi', '0003_auto_20210623_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
    ]
