# Generated by Django 3.2.3 on 2021-07-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeappi', '0004_remove_pokemon_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.CharField(default='dragon', max_length=20),
            preserve_default=False,
        ),
    ]
