# Generated by Django 3.2.3 on 2021-07-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeappi', '0005_pokemon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='type',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.CharField(default='', max_length=20),
        ),
    ]
