print ("enter the following ")
adj_1 = input ("adjetive ")
adj_2 = input ("adjetive ")
occupation = input ("job ")
animals = input ("plural animals ")
animal = input ("single animal ")
noun_1 = input ("noun ")
adj_3 = input ("adjetive ")
appliance = input ("appliance ")
verb = input ("verb ")
noun_2 = input ("noun ")
yell = input ("exclimation ")
noun_plural = input ("plural noun ")

print (f'The {adj_1} {adj_2} {occupation} {animals} are 4 {animals} who are lead by a/an {animal} in the fight against {noun_1}. They strive to protect {noun_plural} from all violence, but their most {adj_3} enemy is the dreaded {appliance}. They also love to {verb} {noun_2}! {yell}, dude!')

