# Generated by Django 3.2.3 on 2021-05-26 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='todoapp.priority'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
