# Generated by Django 3.2.3 on 2021-07-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(default='stare into void', max_length=20),
        ),
    ]
