# Generated by Django 3.2.3 on 2021-07-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_todo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='Low', max_length=200),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
