# Generated by Django 3.2.3 on 2021-05-25 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='text',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDo.todoitem'),
        ),
    ]
