# Generated by Django 3.2.3 on 2021-05-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_auto_20210525_0939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
