# Generated by Django 3.2.3 on 2021-05-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0004_auto_20210525_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='date',
        ),
    ]
