# Generated by Django 3.2.3 on 2021-06-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
